### ISSUE TITLE
Error when running on Windows

### ISSUE THREAD

**Issue by beleta** [sohoffice/angular-universalize-email#11]
When running on Windows `node_modules/.bin/angular-universalize-email` displays the following error:

`Unhandled rejection Error: ENOENT: no such file or directory, open 'C:\C:\Eclipse\Workspaces\workspace.photon\Tutorial\dist\foo-email\styles.css'`.

I have just submitted a PR,  #10, that fixes the error.

**Comment by sohoffice** [comment]
Hi @beleta 

Really appreciated you brought this one up. I don't use Windows myself, but I'll try to reproduce the issue and validate your pull request in the following few days.

**Comment by sohoffice** [comment]
I used one less / when creating the file uri, and it seems to work now.
Can you try version 1.1.4 please ?

**Comment by beleta** [comment]
Yes, it works now. Thank you.
